# Generated by Django 5.1.1 on 2024-10-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('company_approved', models.IntegerField(default=0)),
                ('admin_approved', models.IntegerField(default=0)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='new_app.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='new_app.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerDonation',
        ),
    ]
